config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :messages

  root 'static_pages#index'
  get 'chat' => 'static_pages#chat'
  devise_for :users, :path_prefix => 'auth'
  get 'users_online' => 'users#online'
  resources :users do
    collection do
      get 'user_modal' => 'static_pages#user_modal'
    end
  end

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :body, :user


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_reader :remote_avatar

  before_create :remote_avatar
  before_save :remote_avatar
  before_update :remote_avatar

  has_attached_file :avatar, :styles => {:medium => '300x300>', :thumb => '50x50>'}
  validates_attachment_content_type :avatar, :content_type => ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  has_many :messages

  scope :online, lambda { where('updated_at > ?', 5.minutes.ago) }

  def username
    name ? name : email
  end

  def remote_avatar
    image_email = email.downcase
    image_hash = Digest::MD5::hexdigest(image_email)
    url = "http://www.gravatar.com/avatar/#{image_hash}.png?s=500&d=retro"
    self.avatar = URI.parse(url)

    @remote_avatar = url
  end

  def online?
    updated_at > 10.minutes.ago
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter :user_activity


  private

  def user_activity
    unless current_user.nil?
      current_user.try :touch
    end
  end
end

app/controllers/chat_controller.rb
class ChatController < WebsocketRails::BaseController
  include ActionView::Helpers::SanitizeHelper

  def user_connected
    unless current_user.nil?
      @user = generate_user_json current_user
      broadcast_message 'user.connected', @user
      broadcast_connected_users
    end
  end

  def user_disconnected
    unless current_user.nil?
      @user = generate_user_json current_user
      broadcast_message 'user.disconnected', @user
    end
  end

  def new_message
    @message = Message.new(body: sanitize(message[:body]), user_id: message[:user_id])
    puts @message
    if @message.save
      data = generate_message_json @message
      User.find(@message.user.id).touch
      broadcast_message 'message.new', data
    else
      puts @message.errors.as_json
    end
  end

  def get_history
    @messages = []
    Message.includes(:user).last(20).each do |message|
      json = generate_message_json message
      @messages.push json
    end
    broadcast_message 'messages.history', @messages
  end

  def broadcast_connected_users
    @online_users = []
    User.online.each { |user| @online_users.push generate_user_json user }
    broadcast_message 'user.online', @online_users
  end

  def generate_message_json(data)
    avatar = data.user.avatar.exists? ? data.user.avatar.url(:medium) : data.user.remote_avatar
    {
        :message => {
            :id => data.id,
            :body => sanitize(data.body),
            :created_at => l(data.created_at, :format => :long)
        },
        :user => {
            :id => data.user.id,
            :name => data.user.username,
            :avatar => avatar,
            :link => user_path(data.user)
        }
    }
  end

  def generate_user_json(data)
    {
        :id => data.id,
        :avatar => data.avatar.exists? ? data.avatar.url(:thumb) : data.avatar.remote_url,
        :name => data.username,
        :link => user_path(data.id),
        :quote => "!@user-#{data.id}"
    }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    if @message.save
      render json: @message, status: :created, location: @message
    else
      error
    end
  end

# PATCH/PUT /messages/1
# PATCH/PUT /messages/1.json
  def update
    if @message.update(message_params)
      render json: @message, status: :ok
    else
      error
    end
  end


# DELETE /messages/1
# DELETE /messages/1.json
  def destroy
    @message.destroy
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:user_id, :body)
  end

  def error
    render json: @message.errors, status: :unprocessable_entity
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authenticate_user!, :only =>  [:chat]

  def index

  end

  def chat
    render :layout => 'chat'

  end

  def speedtest

  end

  def user_modal
    unless current_user.nil?
      @last_messages = Message.order(:created_at => :asc).where(:user_id => current_user.id).limit(6)
    end
    render 'chunks/user_modal', :layout => false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /users/online
  def online
    @users = User.online
    respond_to do |format|
      format.html { render :online, :layout => false }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:avatar, :messages)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chunks/user_modal.html.slim
.modal-dialog.user-modal
  .modal-content
    .modal-header.clearfix
      button.close type="button" data-dismiss="modal" &times;
      h4.modal-title#modal-header
        span.row
          - if current_user.nil?
            span.col-md-12
              = t('nd.users.modal.login')
          - else
            span.col-md-5
              a href==user_path(current_user)
                span.glyphicon.glyphicon-user
                |&nbsp;
                = current_user.username
          - unless current_user.nil?
            span.col-md-7
              span.glyphicon.glyphicon-comment
              |&nbsp;
              =t('nd.users.modal.last_messages')
    .modal-body
      - if current_user.nil?
        .row
          .col-xs-12.col-sm-12.col-md-6.col-lg-6
            == render :partial => 'partials/login'
          .col-xs-12.col-sm-12.col-md-6.col-lg-6
            h3 Other actions
            .row
              .btn-group-vertical.col-md-12
                == link_to 'Register', new_user_registration_path, :class => 'btn btn-default'
                == link_to 'Forgot your password?', new_password_path(:user), :class => 'btn btn-default'
        .clearfix
      - else
        .row
          .col-xs-12.col-sm-12.col-md-5.col-lg-5
            div.user-avatar-wrap
              a href==user_path(current_user)
                - if current_user.avatar.exists?
                  == image_tag current_user.avatar.url, :class => 'img-responsive img-rounded img-thumbnail'
                - else
                  == image_tag current_user.remote_avatar, :class => 'img-responsive img-rounded img-thumbnail'
            / @TODO: user info
            .clearfix
            ul.list-group
              li.list-group-item.has-tooltip data-toggle="tooltip" data-placement="top" title="Registered at"
                span.badge
                  span.glyphicon.glyphicon-calendar
                = time_tag current_user.created_at
            |todo
          .col-xs-12.col-sm-12.col-md-7.col-lg-7
            - if @last_messages.any?
              .row
              - for message in @last_messages
                .col-md-6
                  .panel.panel-default
                    .panel-heading == message.created_at
                    .panel-body
                      = message.body
            - else
              |No messages for user
        .clearfix
    .modal-footer
      a.btn.btn-default href="#" class="btn btn-white" data-dismiss="modal" Dismiss
      - unless current_user.nil?
        == link_to('Logout', destroy_user_session_path, :class => 'btn btn-danger')

app/views/layouts/application.html.slim
doctype html
html
  head
    title Дипломный чат
    == stylesheet_link_tag 'application', :media => :all, 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    == render :partial => 'partials/header'
    .container
      == yield
    div.modal.fade#user-modal tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'
    == javascript_include_tag :application, 'data-turbolinks-track' => true
    - if current_page?(chat_path)
      ==javascript_include_tag 'chat'

app/views/layouts/chat.html.slim
doctype html
html
  head
    title Дипломный чат
    == stylesheet_link_tag 'application', :media => :all, 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    == render :partial => 'partials/header'
    #chat-wrap
      .container
        == yield
      div.modal.fade#user-modal tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'
      == javascript_include_tag :application, 'data-turbolinks-track' => true
      - if current_page?(chat_path)
        ==javascript_include_tag 'chat'

app/views/partials/_header.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role='navigation'
  .container
    .navbar-header
      button.navbar-toggle type='button' data-toggle='collapse' data-target='#nd-navbar'
        span.sr-only == t('nd.layout.navbar.toggle_nav')
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href==root_path
        == t('nd.app.name')
    .collapse.navbar-collapse#nd-navbar
      ul.nav.navbar-nav.navbar-right
        li
          a href==root_path
            == t('nd.app.menu.index')
        li
          == link_to 'Chat', chat_path
        li
          a.user-menu-item data-toggle='ajaxModal' data-remote='#{user_modal_users_path}' data-target='#user-modal'
            - if current_user.nil?
              |Login
            - else
              = image_tag current_user.avatar.exists? ? current_user.avatar.url(:thumb) : current_user.remote_avatar, :class => 'img-responsive user-avatar'
              = current_user.username
            b.caret

app/views/partials/_login.html.slim
== semantic_form_for :user, :url => user_session_path do |f|
  == f.input :email
  == f.input :password
  == f.action :submit, :button_html => { :class => 'btn btn-success' }

app/views/static_pages/chat.html.slim
.row#chat-window
  .col-md-9
    .well.well-sm
      #chat data-uri='#{request.host}:3001/websocket'
  .col-md-3
    #users-online
  .clearfix
.row#chat-form
  .col-md-12.message-form
    textarea#message-body placeholder='Enter message' name='message[body]' required='required'
    .cleafix
    button.btn.btn-primary.pull-right#message-send type='button' Send
    .clearfix
    - unless current_user.nil?
      input#message-user type='hidden' name='message[user_id]' value==current_user.id required='required'

app/views/static_pages/index.html.slim
h2 Sup, world!

app/views/users/_form.html.slim
= semantic_form_for @user do |f|
  = f.input :name
  = f.input :avatar, :required => false
  = f.input :password
  = f.input :password_confirmation
  = f.action :submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/online.html.slim
- if @users.any?
  - @users.each do |user|
    .well.well-sm.user data-uid==user.id
      .media
        a.pull-left href='#'
          = image_tag user.avatar.url(:thumb), :class => 'img-rounded img-thumbnail media-object'
        .media-body
          .media-heading
            a href==user_path(user)
              = user.username
          .btn-group.btn-group-sm
            a.btn.btn-default href='#'
              |Poke

app/views/users/profile.html.slim
h1 Users#profile
p Find me in app/views/users/profile.html.slim

app/views/users/show.html.slim
.row#user-header
  .col-xs-12.col-sm-12.col-md-12.col-lg-12
    h2
      = @user.username
      - if current_user.id == @user.id
        .pull-right
          a.btn.btn-info.edit-user href==edit_user_path(@user)
            span.glyphicon.glyphicon-pencil
            = t('nd.users.profile.edit')

.clearfix
.row#user-profile
  .col-xs-12.col-sm-12.col-md-3.col-lg-3#user-info
    .avatar-wrap
      - if @user.avatar.exists?
        = image_tag @user.avatar.url, :class => 'img-responsive img-rounded img-thumbnail'
      - else
        = image_tag @user.remote_avatar, :class => 'img-responsive img-rounded img-thumbnail'
    hr
    .list-group.statistics-wrap
      .list-group-item.register-date
        h4.list-group-item-heading
          span.glyphicon.glyphicon-calendar.pull-right
          = t('nd.users.profile.registered_at')
        p.list-group-item-text= l @user.created_at
      .list-group-item.last-seen
        h4.list-group-item-heading
          span.glyphicon.glyphicon-eye-open.pull-right
          = t('nd.users.profile.last_seen')
        p.list-group-item-text= l @user.updated_at
      .list-group-item.messages-count
        h4.list-group-item-heading
          span.glyphicon.glyphicon-comment.pull-right
          = t('nd.users.profile.messages_count')
        p.list-group-item-text= @user.messages.count
  .col-xs-12.col-sm-12.col-md-9.col-lg-9
    h3= t('nd.users.profile.user_messages')
    .list-group
      - @user.messages.last(10).each do |message|
        .list-group-item